/**
 * Per-manufacturer login hints — what password the user should actually enter.
 * This is the biggest UX win in the whole app: users coming from Blue Iris
 * never know which password each camera wants.
 */

interface AuthHint {
  username: string;
  passwordHint: string;
}

const HINTS: Record<string, AuthHint> = {
  Tapo: {
    username: "Set in the Tapo app under Camera Settings → Advanced → Camera Account",
    passwordHint:
      "Open the Tapo app → tap your camera → Settings (gear) → Advanced Settings → Camera Account. The password you set there.",
  },
  Reolink: {
    username: "Usually 'admin' (the default Reolink username)",
    passwordHint:
      "The admin password you set when you first installed the camera in the Reolink app.",
  },
  Eufy: {
    username: "Auto-generated by Eufy",
    passwordHint:
      "Open the Eufy Security app → your camera → Settings → RTSP Stream. Toggle it on, then copy the username and password Eufy generated.",
  },
  Hikvision: {
    username: "'admin' by default",
    passwordHint:
      "The password you set when first activating the camera (via SADP tool or web UI).",
  },
  Dahua: {
    username: "'admin' by default",
    passwordHint:
      "The password you set during the camera's initial setup. If you never changed it, it might be on a sticker on the camera.",
  },
  Amcrest: {
    username: "'admin' by default",
    passwordHint:
      "The password you set during initial setup in the Amcrest app or web interface.",
  },
  Axis: {
    username: "'root' on older models, 'admin' on newer",
    passwordHint:
      "The root/admin password you set on first access (Axis cameras require this on first boot).",
  },
  Ubiquiti: {
    username: "Set in the UniFi Protect app",
    passwordHint:
      "Set in UniFi Protect under Camera Settings → Advanced → RTSP. RTSP must be enabled.",
  },
};

const GENERIC: AuthHint = {
  username: "Usually 'admin'",
  passwordHint: "The password you set during the camera's initial setup, or in its mobile app.",
};

export function getAuthHint(manufacturer: string | null): AuthHint {
  if (!manufacturer) return GENERIC;
  // Case-insensitive prefix match
  const key = Object.keys(HINTS).find(
    (k) => manufacturer.toLowerCase().includes(k.toLowerCase())
  );
  return key ? HINTS[key] : GENERIC;
}
